# Generated by Django 2.1 on 2018-09-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_domain', models.CharField(max_length=200)),
                ('started_date', models.DateTimeField(verbose_name='date started')),
            ],
        ),
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawler_url', models.CharField(max_length=200)),
                ('manchete_class', models.CharField(max_length=200)),
                ('link_class', models.CharField(max_length=200)),
                ('titulo_class', models.CharField(max_length=200)),
                ('subtitulo_class', models.CharField(max_length=200)),
                ('content_class', models.CharField(max_length=200)),
                ('date_class', models.CharField(max_length=200)),
                ('autor_class', models.CharField(max_length=200)),
                ('started_date', models.DateTimeField(verbose_name='date started')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Agent')),
            ],
        ),
    ]
