# Generated by Django 2.1 on 2018-09-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=200)),
                ('subtitulo_noticia', models.CharField(max_length=200)),
                ('link_noticia', models.CharField(max_length=200)),
                ('content_noticia', models.TextField()),
                ('date_noticia', models.DateField()),
                ('autor_noticia', models.CharField(max_length=200)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Crawler')),
            ],
        ),
    ]
