# Generated by Django 2.1.5 on 2019-02-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_agent_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor_noticia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link_noticia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo_noticia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo_noticia',
            field=models.CharField(max_length=1000),
        ),
    ]
