# Generated by Django 2.1.5 on 2019-02-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
