# Generated by Django 2.1.7 on 2019-04-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='crawler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='main.Crawler'),
        ),
    ]
