# Generated by Django 2.1.7 on 2019-04-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190404_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler', to='main.Agent'),
        ),
    ]
